provider: azureopenai
endpoint: ${AZURE_OPENAI_ENDPOINT}
api_key: ${AZURE_OPENAI_KEY}
api_version: "2024-10-21"

models:
  gpt-4o:
    deployment: gpt-4o-deployment
    temperature: 0.0
    max_tokens: 4096
    top_p: 1.0
    frequency_penalty: 0
    presence_penalty: 0
    
  gpt-4o-mini:
    deployment: gpt-4o-mini-deployment
    temperature: 0.0
    max_tokens: 2048
    
batch:
  threshold: 100
  size: 20
  max_retries: 3
  retry_delay: 1