provider: openai
api_key: ${OPENAI_API_KEY}

models:
  gpt-4o:
    temperature: 0.0
    max_tokens: 4096
    
  gpt-5:
    temperature: 0.0
    max_tokens: 8192
    reasoning_effort: medium
    reasoning_strategy: chain_of_thought
    
  o1:
    temperature: 0.0
    max_completion_tokens: 10000
    
  o3:
    temperature: 0.0
    max_completion_tokens: 15000
    reasoning_depth: high

batch:
  threshold: 50
  size: 10